name: Build and deploy Python app to Azure Web App

env:
  AZURE_WEBAPP_NAME: JavaToPython
  PYTHON_VERSION: '3.10'
  STARTUP_COMMAND: 'gunicorn --bind=0.0.0.0 --timeout 600 web_app:app'

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Sanity check for required files
        run: |
          test -f requirements.txt
          test -f web_app.py || (echo "Missing web_app.py (entry point)"; exit 1)

      - name: Create deployment artifact
        run: |
          mkdir package
          shopt -s extglob
          cp -R !(package) package/ || true
          # prune venv if created locally
          rm -rf package/venv
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: package/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app
          path: .

      - name: Verify publish profile secret present
        run: |
          if [ -z "${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}" ]; then
            echo "AZURE_WEBAPP_PUBLISH_PROFILE secret is missing."
            exit 1
          fi

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
          startup-command: ${{ env.STARTUP_COMMAND }}
