name: Build and deploy Python app to Azure Web App

env:
  AZURE_WEBAPP_NAME: JavaToPython          # <-- set to your Azure Web App name
  PYTHON_VERSION: '3.10'                    # Match project’s Python version
  STARTUP_COMMAND: 'gunicorn --bind=0.0.0.0 --timeout 600 web_app:app'

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
            python-version: ${{ env.PYTHON_VERSION }}
            cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Optional: run unit tests (uncomment if you add tests)
      # - name: Run tests
      #   run: |
      #     pytest -q

      - name: Prepare artifact (prune unneeded directories)
        run: |
          rm -rf .git
          rm -rf __pycache__
          rm -rf outputs || true
          rm -rf uploads || true
          find . -type d -name "__pycache__" -prune -exec rm -rf {} +
          # Ensure requirements.txt present
          test -f requirements.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            .
            !venv/
            !**/*.pyc
            !**/__pycache__/
            !outputs/
            !uploads/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: none
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app
          path: .

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          startup-command: ${{ env.STARTUP_COMMAND }}
